redis:
  image: redis:2.8
registry:
  restart: always
  image: registry:2
  ports:
    - 80:5000
  volumes:
    - ./registry-config.yml:/etc/docker/registry/config.yml
    - ${CERTS_PATH}:/certs
    - ${AUTH_PATH}:/auth
  links:
    - redis:redis
